### ISSUE TITLE
From where i can get transaction ID after success payment

### ISSUE THREAD

**Issue by abdullahehab** [tabby-ai/tabby_flutter_inapp_sdk#11]
I have integrate tabby_flutter_inapp_sdk with my flutter application 
after payment success there are as success message display of screen and print "authorized" in console
i wanna get transaction id after payment success

**Comment by kuznetsov-from-wonderland** [comment]
Hey @abdullahehab 

`Future<TabbySession> createSession(TabbyCheckoutPayload payload);`

`TabbySession` contains the `paymentId` you're looking for.
