### ISSUE TITLE
Update to latest dependencies

### ISSUE THREAD

**Issue by hit-flutter** [tabby-ai/tabby_flutter_inapp_sdk#14]
Please update the dependencies to the latest. Mainly `http`.

Thanks.

**Comment by isa-sabbagh** [comment]
I got the same error. 

Resolving dependencies...
Because every version of tabby_flutter_inapp_sdk depends on http ^0.13.4 and [my app] depends on http ^1.1.0, tabby_flutter_inapp_sdk is forbidden.
So, because fstore depends on tabby_flutter_inapp_sdk ^1.4.0, version solving failed.

**Comment by kuznetsov-from-wonderland** [comment]
https://github.com/tabby-ai/tabby_flutter_inapp_sdk/pull/18
