### ISSUE TITLE
session create status: 302 

### ISSUE THREAD

**Issue by fahmidul** [tabby-ai/tabby_flutter_inapp_sdk#15]
session create status: 302 
What does it mean by this status code? 
From where I can get details of statuses? 

![image](https://github.com/tabby-ai/tabby_flutter_inapp_sdk/assets/22258130/8bbad643-33e4-4da4-9ddd-29c3eb6dffe5)

**Comment by pushkar2113** [comment]
same I'm also getting same error.



<img width="1254" alt="Screenshot 2023-10-16 at 1 40 38 PM" src="https://github.com/tabby-ai/tabby_flutter_inapp_sdk/assets/137037578/4701676a-66e6-4268-84e0-7ff4ea0f3276">




<img width="795" alt="Screenshot 2023-10-16 at 1 38 23 PM" src="https://github.com/tabby-ai/tabby_flutter_inapp_sdk/assets/137037578/9840f0c7-0165-41fe-94a7-e21f5e75da03">

**Comment by Aseel-Khatri** [comment]
I am also facing this issue in staging environment, any guide, what am I missing?
@kuznetsov-from-wonderland

**Comment by kuznetsov-from-wonderland** [comment]
Please use `Environment.production`
This is ok, since you're operating with the test key, given by Tabby integrations team.

**Comment by Amryasin** [comment]
i use this solution but not working get 401

**Comment by kuznetsov-from-wonderland** [comment]
Please use `Environment.production`

**Comment by kuznetsov-from-wonderland** [comment]
> i use this solution but not working get 401

```
TabbySDK().setup(
    withApiKey: '', // Put here your Api key, given by the Tabby integrations team
  );
```

**Comment by Amryasin** [comment]
thaks for replay but the key i have is pk_test_xxxxxxxxxxxxxxxxxx not a production key

**Comment by kuznetsov-from-wonderland** [comment]
Thanks! That's expected. First you test with `pk_test_xxxxxxxxxxxxxxxxxx` which will end up creating fake transations in Production. Then ask your Tabby Account Manager to provide you `pk_xxxxxxxxxxxxxxxxxx` real key.

**Comment by Amryasin** [comment]
but i cant't create a fake transations using pk_test_xxxxxxxxxxxxxxxxxx on production and when change it to stage get 302

**Comment by kuznetsov-from-wonderland** [comment]
Please email me at ilya.kuznetsov@tabby.ai and kseniya.ismailova@tabby.ai ? 
We'll provide you proper support on your issue.
