### ISSUE TITLE
Unable to use latest flutter_inappwebview

### ISSUE THREAD

**Issue by AhmadEshbailat** [tabby-ai/tabby_flutter_inapp_sdk#23]
/Users/ride/.pub-cache/hosted/pub.dev/flutter_inappwebview-5.8.0/ios/Classes/InAppWebView/InAppWebView.swift:2833:17

**Comment by LeDrOxx** [comment]
@AhmadEshbailat i created a PR for this issue, in the meantime you can use :

tabby_flutter_inapp_sdk:
    git:
      url: https://github.com/LeDrOxx/tabby_flutter_inapp_sdk.git
      ref: inappwebview_update

**Comment by kuznetsov-from-wonderland** [comment]
Hey, we're going to push the new version of the SDK on Monday 30.09.24. Please stay tuned!

**Comment by kuznetsov-from-wonderland** [comment]
Please find https://pub.dev/packages/tabby_flutter_inapp_sdk/versions/1.6.0 released
