### ISSUE TITLE
Missing currencies 

### ISSUE THREAD

**Issue by yossefEl** [tabby-ai/tabby_flutter_inapp_sdk#9]
I found that there are few currencies for the mobile package.<br>`enum Currency { aed, sar, kwd, bdh, egp }` , while in the web version, the currency is dynamic and can be provided as a String<br>For example, the **QAR currency is missing in the mobile package but the payment can proceed with it in the web**

**Comment by kuznetsov-from-wonderland** [comment]
Hey @yossefEl  
We've just released v1.2.0 with Qatar support.
